# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install Chromium for Selenium
RUN apt-get update && \
    apt-get install -y chromium && \
    ln -s /usr/bin/chromium /usr/bin/google-chrome && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . /app

# Expose nothing - stdio mode
# Default command
CMD ["python", "main.py", "--transport", "stdio"]
